### ISSUE TITLE
Tried converting an SVG but it ends up littered with 'NaN'

### ISSUE THREAD

**Issue by transat** [quassummanus/SVG-to-SwiftUI#2]
Tried converting an SVG but it ends up littered with 'NaN', and causes errors in XCode.

e.g.

`path.addCurve(to: CGPoint(x: NaN*width, y: NaN*height),control1: CGPoint(x: -0.00809*width, y: 0),control2: CGPoint(x: NaN*width, y: NaN*height))`

**Comment by bring-shrubbery** [comment]
Thanks for feedback! Could you provide at least a snippet of SVG that you tried converting? If you do, I will be able to fix it today!

**Comment by transat** [comment]
Sure thing. Here is the whole SVG:

<svg id="Capa_1" enable-background="new 0 0 511.531 511.531" height="512" viewBox="0 0 511.531 511.531" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m457.469 396.228c31.359-42.9 47.91-93.644 47.91-147.072 0-42.419-10.833-84.316-31.326-121.161-4.56-8.202-17.879-1.285-13.108 7.291 19.256 34.621 29.435 73.996 29.435 113.87 0 101.147-66.178 191.866-161.779 223.074l-7.515-20.646c40.671-13.153 77.139-38.817 103.353-72.904 28.776-37.419 43.986-82.208 43.986-129.525 0-117.26-95.398-212.658-212.659-212.658s-212.659 95.4-212.659 212.659c0 28.718 5.63 56.582 16.733 82.817 3.659 8.643 17.639 3.191 13.813-5.846-10.316-24.376-15.546-50.272-15.546-76.972 0-108.989 88.669-197.658 197.659-197.658s197.659 88.669 197.659 197.658c0 85.912-56.188 162.363-137.474 188.322l-38.848-106.727 44.253-121.583c2.126-1.067 4.094-2.405 5.865-3.964 23.423 37.812 12.061 88.859-24.673 113.59-7.755 5.221.172 17.963 8.377 12.443 45.761-30.809 57.498-95.437 24.857-140.178 5.396-21.934-17.719-41.038-38.323-31.58-26.211-12.173-57.175-12.174-83.388.001-20.558-9.431-43.729 9.617-38.322 31.581-40.07 54.923-11.638 135.504 53.672 153.433l-33.84 92.982c-43.892-14.007-81.538-42.949-106.536-82.102-5.052-7.911-17.923-.198-12.643 8.072 26.78 41.943 67.063 72.997 114.045 88.136l-7.515 20.649c-95.602-31.208-161.78-121.927-161.78-223.074 0-129.366 105.247-234.613 234.613-234.613 72.461 0 141.622 34.081 185.863 91.419 2.712 3.521 8.102 3.869 11.241.722l17.073-17.072c7.211-7.212 7.211-18.945 0-26.157l-28.476-28.476c-7.211-7.211-18.945-7.211-26.156 0l-12.5 12.5c-86.47-63.227-207.679-63.367-294.137-.044l-12.454-12.456c-7.21-7.211-18.944-7.211-26.156 0l-28.475 28.475c-7.07 7.072-7.086 19.07 0 26.157l12.455 12.454c-31.09 42.449-47.891 93.476-47.891 147.091 0 53.428 16.551 104.172 47.91 147.072l-12.473 12.474c-7.071 7.07-7.086 19.069 0 26.156l28.476 28.476c7.061 7.061 19.079 7.077 26.156 0l12.537-12.537c21.018 15.335 44.364 27.408 69.042 35.534-2.492 5.035-5.146 13.537 2.095 16.173l23.588 8.586c3.836 1.394 8.215-.643 9.613-4.482l3.944-10.836c25.609 3.989 51.843 3.989 77.453 0l3.944 10.836c1.398 3.839 5.778 5.877 9.613 4.482l23.588-8.586c7.241-2.636 4.587-11.138 2.095-16.173 24.678-8.126 48.024-20.2 69.042-35.534l12.537 12.536c7.061 7.061 19.079 7.077 26.156 0l28.476-28.476c7.068-7.07 7.088-19.07 0-26.155zm-31.551-350.642c1.648-1.366 3.295-1.366 4.943 0l28.476 28.476c1.365 1.648 1.365 3.295 0 4.942l-11.159 11.158c-10.055-12.142-21.272-23.348-33.431-33.405zm-373.724 33.418c-1.365-1.647-1.365-3.295 0-4.942l28.476-28.476c1.648-1.366 3.295-1.366 4.943 0l11.14 11.14c-6.036 5.006-11.878 10.311-17.493 15.926s-10.919 11.456-15.925 17.492zm33.419 373.723c-1.648 1.366-3.295 1.366-4.943 0l-28.476-28.476c-1.365-1.647-1.365-3.294 0-4.941l11.152-11.152c10.082 12.168 21.315 23.337 33.468 33.367zm170.153-63.354 20.52 56.38c-13.6 1.391-27.453 1.391-41.041 0zm29.434-218.803c-4.359 7.457-4.994 16.953-1.541 24.89l-27.894 76.644-27.894-76.644c3.453-7.936 2.817-17.432-1.541-24.89 18.751-7.049 40.12-7.049 58.87 0zm-86.96 2.135c10.806-3.937 21.241 8.209 15.062 18.338-1.188 1.947-1.425 4.328-.646 6.472l35.127 96.52-5.376 14.772-39.254-107.837c-.779-2.141-2.489-3.811-4.647-4.54-10.92-3.689-11.228-19.735-.266-23.725zm-26.357 76.451c0-15.784 4.276-30.796 12.426-43.953 1.77 1.559 3.738 2.897 5.865 3.964l44.074 121.076c-36.505-9.617-62.365-42.714-62.365-81.087zm29.682 245.274-9.493-3.455 106.803-293.46c.78-2.144.542-4.524-.646-6.472-8.078-13.241 11.527-26.398 20.714-13.814 4.917 6.735 2.21 16.455-5.918 19.201-2.158.729-3.868 2.399-4.647 4.54zm20.712-13.05 7.688-21.123c17.125 2.064 34.474 2.063 51.6 0l7.688 21.122c-22.083 3.147-44.892 3.147-66.976.001zm87.689 13.05-46.218-126.986 5.374-14.766 50.337 138.297zm149.37-70.179-28.476 28.476c-1.648 1.366-3.295 1.366-4.943 0l-11.201-11.201c12.153-10.031 23.387-21.2 33.468-33.368l11.152 11.152c1.365 1.647 1.365 3.294 0 4.941z"/></svg>

Thanks for the quick response!

**Comment by bring-shrubbery** [comment]
Alright, the issue seems to be a bit deeper than I expected so it might take some time. If you can get at least a demo version of [sketch](https://www.sketch.com), import it there, and then right-click on your SVG and select `Copy SVG code`, then I know it works fine. I'll make sure this tool supports it this week, but can't do it in one day unfortunately 😭

**Comment by transat** [comment]
Cheers. No rush on my account.

**Comment by bring-shrubbery** [comment]
@transat Hey, I finally found time for this project! Your SVG code will work now, just don't forget to add `.fill().frame(width: 200, height: 200)` when creating the shape in SwiftUI. Here's a quick [link](https://quassummanus.github.io/SVG-to-SwiftUI/) for convenience 😁

**Comment by bring-shrubbery** [comment]
Btw, I extracted the compiler code from this repo and there's now an [npm package](https://www.npmjs.com/package/svg-to-swiftui-core) that does all the transpiling work. I'm telling you this because I added your SVG code as one of the tests, and the test is named after you 😃, so hopefully, you don't mind that!

**Comment by transat** [comment]
Great stuff. Cheers! And yes, happy for my GitHub username to be immortalised in a test.
